---
stages:
  - build
  - git-sync

build:
  stage: build
  script:
    - docker login -u="${QUAY_IO_USER}" -p="${QUAY_IO_PASSWORD}" quay.io
    - bundle install --path vendor/bundle
    - bundle exec rake rev
    - bundle exec rake lint
    - bundle exec rake update_base_images
    - bundle exec rake build
    - bundle exec rake spec
    - bundle exec rake push
  only:
    - master
  except:
    - triggers
  tags:
    - docker-build

git-sync:
  script:
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | base64 -d | ssh-add -
    - git sync-remote
        git@github.com:${CI_PROJECT_PATH}.git
        git@git.boo.tc:${CI_PROJECT_PATH}.git
  stage: git-sync
  image: quay.io/bootc/github-gitlab-sync:latest
  only:
    - triggers

# vim: ai ts=2 sw=2 et sts=2 ft=yaml
